POST http://localhost:8080/project/api/auth/login
Content-Type: application/json

{
  "email": "a.a@a.a",
  "password": "1234"
}

###
POST http://localhost:8080/project/api/users
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhLmFAYS5hIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNjM3ODg2MjMxfQ.W2NOVQmoOcdqplzAMNvk7vMjY7x7blR-qRUgKtdTS1cgeBp_Y5oKH98wP_xmQ7s5Gz1JkXSbJHCfd_5gv8_LACMWD19bqOMTrkeudGnV6p9G9cWjfdeUHuYggIT37JTKwX2HFKrYZMZtnsjk8rGyjoUZp7NHqlR0HTgCVani3LxbDE14fdQ9otowMmUMULXNv_zk8TUtbm7TPMksawZ_n1g-_W9-qBD6sJeOEyRuzXXXFIl9DiGhNxJH2KqTh5dtop76fbTdQbFmRHb5XVZoN99gpCIqr0bmMTK7LZMv0mBoL_xM0LoRt0icNMEJRbJjBOxqT3ines59uyPHJo9ZMQ
Content-Type: application/json

{
  "tipo": "Administrador",
  "email": "b.b@b.b",
  "name": "b",
  "password": "1234"
}

###
GET http://localhost:8080/project/api/users
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhLmFAYS5hIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNjM3ODg2MjMxfQ.W2NOVQmoOcdqplzAMNvk7vMjY7x7blR-qRUgKtdTS1cgeBp_Y5oKH98wP_xmQ7s5Gz1JkXSbJHCfd_5gv8_LACMWD19bqOMTrkeudGnV6p9G9cWjfdeUHuYggIT37JTKwX2HFKrYZMZtnsjk8rGyjoUZp7NHqlR0HTgCVani3LxbDE14fdQ9otowMmUMULXNv_zk8TUtbm7TPMksawZ_n1g-_W9-qBD6sJeOEyRuzXXXFIl9DiGhNxJH2KqTh5dtop76fbTdQbFmRHb5XVZoN99gpCIqr0bmMTK7LZMv0mBoL_xM0LoRt0icNMEJRbJjBOxqT3ines59uyPHJo9ZMQ
Content-Type: application/json
