### ADMIN
POST http://localhost:8080/project/api/auth/login
Content-Type: application/json

{
  "email": "a.a@a.a",
  "password": "1234"
}

### GET ALL USERS
GET http://localhost:8080/project/api/users
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjEyMDR9.U19w9xvg1BvfQGPJfILGp2aRSQZuiZqg8lkH-RBHn7CVrlB8kHtqCMZ_n03zaH-LRWd6EfC2GWAktgGB2wFZeh8RbXT5IMqkI6HvkdaxnsmWOhrbeWH8IXTYsSAtn5IRdJjtKccJsrLmtypD_1ON2DazSH5t21nld_hIS7sIzKsWhPJ81MEnqke8k1dHRd73eMVDb3hXGWDtFOW9AmxnurUZjnD6Z2-X5ptCbc52Uu7octvdB78xZmtQDBaOHXGpphHbba1tWnw_3KIt6X1tn7xXAY-oTYV5terToKLv6n0YKCOE7UwmZtkxDITdrXxrrCQCHG62tOevMC4YF_huTg

### GET ADMINISTRATOR
GET http://localhost:8080/project/api/administradores/a.a@a.a
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjEyMDR9.U19w9xvg1BvfQGPJfILGp2aRSQZuiZqg8lkH-RBHn7CVrlB8kHtqCMZ_n03zaH-LRWd6EfC2GWAktgGB2wFZeh8RbXT5IMqkI6HvkdaxnsmWOhrbeWH8IXTYsSAtn5IRdJjtKccJsrLmtypD_1ON2DazSH5t21nld_hIS7sIzKsWhPJ81MEnqke8k1dHRd73eMVDb3hXGWDtFOW9AmxnurUZjnD6Z2-X5ptCbc52Uu7octvdB78xZmtQDBaOHXGpphHbba1tWnw_3KIt6X1tn7xXAY-oTYV5terToKLv6n0YKCOE7UwmZtkxDITdrXxrrCQCHG62tOevMC4YF_huTg

### NEW ADMINISTRATOR
POST http://localhost:8080/project/api/administradores
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjEyMDR9.U19w9xvg1BvfQGPJfILGp2aRSQZuiZqg8lkH-RBHn7CVrlB8kHtqCMZ_n03zaH-LRWd6EfC2GWAktgGB2wFZeh8RbXT5IMqkI6HvkdaxnsmWOhrbeWH8IXTYsSAtn5IRdJjtKccJsrLmtypD_1ON2DazSH5t21nld_hIS7sIzKsWhPJ81MEnqke8k1dHRd73eMVDb3hXGWDtFOW9AmxnurUZjnD6Z2-X5ptCbc52Uu7octvdB78xZmtQDBaOHXGpphHbba1tWnw_3KIt6X1tn7xXAY-oTYV5terToKLv6n0YKCOE7UwmZtkxDITdrXxrrCQCHG62tOevMC4YF_huTg
Content-Type: application/json

{
  "email": "d.d@d.d",
  "name": "b",
  "password": "1234"
}

### UPDATE ADMINISTRATOR
PUT http://localhost:8080/project/api/administradores/a.a@a.a
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjEyMDR9.U19w9xvg1BvfQGPJfILGp2aRSQZuiZqg8lkH-RBHn7CVrlB8kHtqCMZ_n03zaH-LRWd6EfC2GWAktgGB2wFZeh8RbXT5IMqkI6HvkdaxnsmWOhrbeWH8IXTYsSAtn5IRdJjtKccJsrLmtypD_1ON2DazSH5t21nld_hIS7sIzKsWhPJ81MEnqke8k1dHRd73eMVDb3hXGWDtFOW9AmxnurUZjnD6Z2-X5ptCbc52Uu7octvdB78xZmtQDBaOHXGpphHbba1tWnw_3KIt6X1tn7xXAY-oTYV5terToKLv6n0YKCOE7UwmZtkxDITdrXxrrCQCHG62tOevMC4YF_huTg
Content-Type: application/json

{
  "name": "Alberto"
}

### DELETE ADMINISTRATOR
DELETE http://localhost:8080/project/api/administradores/d.d@d.d
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjEyMDR9.U19w9xvg1BvfQGPJfILGp2aRSQZuiZqg8lkH-RBHn7CVrlB8kHtqCMZ_n03zaH-LRWd6EfC2GWAktgGB2wFZeh8RbXT5IMqkI6HvkdaxnsmWOhrbeWH8IXTYsSAtn5IRdJjtKccJsrLmtypD_1ON2DazSH5t21nld_hIS7sIzKsWhPJ81MEnqke8k1dHRd73eMVDb3hXGWDtFOW9AmxnurUZjnD6Z2-X5ptCbc52Uu7octvdB78xZmtQDBaOHXGpphHbba1tWnw_3KIt6X1tn7xXAY-oTYV5terToKLv6n0YKCOE7UwmZtkxDITdrXxrrCQCHG62tOevMC4YF_huTg

### HEALTH PROFESSIONAL
POST http://localhost:8080/project/api/auth/login
Content-Type: application/json

{
  "email": "f.f@f.f",
  "password": "1234"
}

### GET HEALTH PROFESSIONAL
GET http://localhost:8080/project/api/profissionaisdesaude/h.h@h.h
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjI4MDd9.IO3m0jy_UJWsR3kJYlpvRomTzPXlXd4eOZTKT7NsbgOSLiOt2E2848CS6_PzLP_yii_fd9b_kzCc8T2OUOaChDD8z0nWe7ThTGf6AJZsX9qn0Ru40FnJlPnXrro54DLZ1COppFsYVdw1O76jXbywCZK76dMi-tx2a6qCRpDrAXyIyAlxhCm4LLmcTQmS17BQIsPMqvcYFiCmlwWfJq5nKi7NAzL6qHOhZzinmttuNHZET8i5-jwOZFkkoNnFSmnGR7XBkJP1sMS777PDVxlsEI1aH6Ic61jJLhKA_AcGdyYWqZCgnfN1nvTxxWcjB2v7Kq1ZknQFzBYfjC7QmFd8Kg

### NEW HEALTH PROFESSIONAL
POST http://localhost:8080/project/api/profissionaisdesaude
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjI4MDd9.IO3m0jy_UJWsR3kJYlpvRomTzPXlXd4eOZTKT7NsbgOSLiOt2E2848CS6_PzLP_yii_fd9b_kzCc8T2OUOaChDD8z0nWe7ThTGf6AJZsX9qn0Ru40FnJlPnXrro54DLZ1COppFsYVdw1O76jXbywCZK76dMi-tx2a6qCRpDrAXyIyAlxhCm4LLmcTQmS17BQIsPMqvcYFiCmlwWfJq5nKi7NAzL6qHOhZzinmttuNHZET8i5-jwOZFkkoNnFSmnGR7XBkJP1sMS777PDVxlsEI1aH6Ic61jJLhKA_AcGdyYWqZCgnfN1nvTxxWcjB2v7Kq1ZknQFzBYfjC7QmFd8Kg
Content-Type: application/json

{
  "email": "h.h@h.h",
  "name": "Hero",
  "password": "1234"
}

### UPDATE HEALTH PROFESSIONAL
PUT http://localhost:8080/project/api/profissionaisdesaude/h.h@h.h
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjI4MDd9.IO3m0jy_UJWsR3kJYlpvRomTzPXlXd4eOZTKT7NsbgOSLiOt2E2848CS6_PzLP_yii_fd9b_kzCc8T2OUOaChDD8z0nWe7ThTGf6AJZsX9qn0Ru40FnJlPnXrro54DLZ1COppFsYVdw1O76jXbywCZK76dMi-tx2a6qCRpDrAXyIyAlxhCm4LLmcTQmS17BQIsPMqvcYFiCmlwWfJq5nKi7NAzL6qHOhZzinmttuNHZET8i5-jwOZFkkoNnFSmnGR7XBkJP1sMS777PDVxlsEI1aH6Ic61jJLhKA_AcGdyYWqZCgnfN1nvTxxWcjB2v7Kq1ZknQFzBYfjC7QmFd8Kg
Content-Type: application/json

{
  "name": "Halt"
}

### DELETE HEALTH PROFESSIONAL
DELETE http://localhost:8080/project/api/profissionaisdesaude/h.h@h.h
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjI4MDd9.IO3m0jy_UJWsR3kJYlpvRomTzPXlXd4eOZTKT7NsbgOSLiOt2E2848CS6_PzLP_yii_fd9b_kzCc8T2OUOaChDD8z0nWe7ThTGf6AJZsX9qn0Ru40FnJlPnXrro54DLZ1COppFsYVdw1O76jXbywCZK76dMi-tx2a6qCRpDrAXyIyAlxhCm4LLmcTQmS17BQIsPMqvcYFiCmlwWfJq5nKi7NAzL6qHOhZzinmttuNHZET8i5-jwOZFkkoNnFSmnGR7XBkJP1sMS777PDVxlsEI1aH6Ic61jJLhKA_AcGdyYWqZCgnfN1nvTxxWcjB2v7Kq1ZknQFzBYfjC7QmFd8Kg

### ILL PERSON
POST http://localhost:8080/project/api/auth/login
Content-Type: application/json

{
  "email": "p.p@p.p",
  "password": "1234"
}

### GET ALL ILL PEOPLE
GET http://localhost:8080/project/api/doentes
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJmLmZAZi5mIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zpc3Npb25hbERlU2F1ZGUiXSwiZXhwIjoxNjQwOTIwMzgxfQ.aL5aHM7Yq6wCRQ9o65VHwqHoMSXnqsI_Yk2ZHLv7iz_IbwOm6aPz8L8jGSA-jXTn2yYUEisK8IHrommCbA6fa60maRXXyNnil2MRsNfzEsxMbW5GFuxr5g9PevFpcSGpyx2R-P0RtzIcEB37fjGvsb8bj6iBrOkb-c_TlKs-6Dl14uBxVaaK6Am_Q5qNfdV2r31r77mATr-3YiibDUg1wEe-dWr2H9IbwFx5ZH7HmTZrpqLJGxdNffy0_WRuSn4PRNiyXuDx1yw0mgFCaaJcQAwBicW1iRMZylJV5SyXCWBrAikaeYM1DK5Yn32EYrM27NrnZMRqXVDHLMgD_oSQWw

### GET ILL PERSON
GET http://localhost:8080/project/api/doentes/p.p@p.p
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJmLmZAZi5mIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zpc3Npb25hbERlU2F1ZGUiXSwiZXhwIjoxNjQwOTE5OTEzfQ.O2ViuX9ZGe9h1hcU9xxrU6reHdHGZxe9TuK2FPQAzj_POoY_MC6uVhirnZoCEzPq8LbfSHCW-a5pJ2GHQRAV3aPPxub290bUvSZ7kwxLf8OBWbQXG7VN7xm8MeBw_t8BPsSfmZ5QnAc6CaFEU3-PHWMyLGa-f62e-mC0n60G-Knr-wfcWmaVFPo-JamffYL_R_CuxggOEdCeX4L1cDbhOTB5NjZ35TfK416laXtIwcgTt16XSptp-qiAGnzAArDbF3Zssqy_4yHqT467FbQt2rWrl05o1RH-0emHVnW1lV_36sBJ4pNiPG5KKuDqIM5EOwfOcxiU1YEebsxSmlMLAQ

### UPDATE ILL PERSON
PUT http://localhost:8080/project/api/doentes/p.p@p.p
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwLnBAcC5wIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjAyODd9.AmsHNByBfxVUUL_lstqtSgcA2D-VW-d2QWK638buEWjPpcMSruyjN_6W-eTgjrRpABVsyf_vUDhWsJskM6ZemgdjbvcRBMHvn4E8fYakD-8Fgs9PIl-IGnMEYn_pZyjHF5UbuNXKXX3MYNABaxIGt9LigzDg0uS67U9jJeTHVONASn8FIxEp0SA3aerC0oKeFNE2E618_4coI9ReeoqRVCZTuLC_QltPI7P1dAolrkZHEVrlfkkP7GRn-DO8RyXqHuDVTbZLz4vtoUiyrJEcAV5l63VOiC4adoWNExYMEZ15texqlXPw6H8tx9FVWteZWpyYaZs4weB_7ZOa8CCegQ
Content-Type: application/json

{
  "name": "Pedro",
  "idade": "40",
  "altura": "12.4",
  "peso": "1000"
}

### DELETE ILL PERSON
DELETE http://localhost:8080/project/api/doentes/p.p@p.p
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJyLnJAci5yIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkRvZW50ZSJdLCJleHAiOjE2NDA5MjAxNTh9.efinhiu6NGv0WFDqXUFKGSNuInjJ6ohAXDQx8X52ICHcQIZA_Bh7R9Bsjf5WFSMnPty2JbxyO4eQQo1F1LWhBBZDXGugUfkxMn6bzRdFO8GbrlMgQz5dhJf824eIhL97GfD4kcQmR8cAxDjYm_WAOupV7tIjB1XJa7CTOa6vhfTm1lDoTkEwLxxxsEYb-xFESk2MvqosAkFztva11lkIrTIbhk9bqeECrbE8Kt52L9EH5lnCnPY2q18elvEb-LY1jLkqdHUn9oELlBQng1aSGeZg0uxb85NrUV-m9lIDgcdNuDZVuNDyt8qnEMl88Ghw4Oj9Wcd1Yl5BczEYZWGVpg

### POST API OBSERVACOES
PUT http://localhost:3000/api/observacoes/4/update
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJmLmZAZi5mIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zpc3Npb25hbERlU2F1ZGUiXSwiZXhwIjoxNjQxMjQxMzEwfQ.TO4hGmQI1zb-kS5YVp5oMzME-U_9U4HHF5YRnNuKxnMDetUu5TZD0gDHDUY89Sq5vu93QL3RmqManQHVkuMHit_6cMTAKIqCmRp85iEwrcSiYPY2W8wKVyLaPk5UMBhEOnNrNGINRcpXQaeh2oZyHMs3EK2-d-Cxg5nUpPVlLhGEX6dAI1NfUOt8ZOKDHVrUKpcoYdrnFPUU0O6IBOLume7H2IkaadTe2DP6qp2iT9CDB8Gw8EB0dDjHo-nmONsoJlVXl9Yn8g-vmadtvsLl_gulSLxzPBtt63YKK2xDdjOP18vJfbdGC21srvHv0DNFHG_gwKGNPZ8MvnIvzEyYeQ
Content-Type: application/json

{
  "doenteEmail": "r.r@r.r",
  "profissionalDeSaudeEmail": "f.f@f.f",
  "nomeDadoBiomedico": "Altura",
  "data": "2000-01-01",
  "valorQuantitativo": 100,
  "valorQualitativo": "Alto"
}

### GET ALL DADOS BIOMEDICOS
GET http://localhost:8080/project/api/dadosbiomedicos/Altura
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJmLmZAZi5mIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zpc3Npb25hbERlU2F1ZGUiXSwiZXhwIjoxNjQxMjcxMjY2fQ.UnpL5Vb4kiikxmhVLx5s9jKBV4IQnAYBCGKI42XXDAdgwe45d-cOmSJAZwFUzRrI9K9YkVsj8HXjIyLCXvaIsVZxZzdbL-5HlQcDVuerCZXGuAgRlCvRYrVmvwdI81ahovtEy60fOemkHGobRW6hMBMnlqMcwImXOj6HKhLaWACuQEqmw5bC4YTS7RK2gG6ydnkWZy6Er3BjV6EGzgADWLfiIVFTz071q8uUQg2AEHGXRrKMlq3W7ki7xf867aseR14zMXnLb_AnSxTbh94DaWQYs4gvgQ-IczlxOoVDP13xVejzApHjSEj6tHqse4lr7Ha4oHY0tomvdQVNGDJoKA


### GET OBSERVACAO
GET http://localhost:8080/project/api/observacoes/4
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJmLmZAZi5mIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zpc3Npb25hbERlU2F1ZGUiXSwiZXhwIjoxNjQxMjcxMjY2fQ.UnpL5Vb4kiikxmhVLx5s9jKBV4IQnAYBCGKI42XXDAdgwe45d-cOmSJAZwFUzRrI9K9YkVsj8HXjIyLCXvaIsVZxZzdbL-5HlQcDVuerCZXGuAgRlCvRYrVmvwdI81ahovtEy60fOemkHGobRW6hMBMnlqMcwImXOj6HKhLaWACuQEqmw5bC4YTS7RK2gG6ydnkWZy6Er3BjV6EGzgADWLfiIVFTz071q8uUQg2AEHGXRrKMlq3W7ki7xf867aseR14zMXnLb_AnSxTbh94DaWQYs4gvgQ-IczlxOoVDP13xVejzApHjSEj6tHqse4lr7Ha4oHY0tomvdQVNGDJoKA
